### ISSUE TITLE
Site Geological Restrictions 

### ISSUE THREAD

**Issue by gatedude** [x3labs/harvest-art#12]
I don't think it's anything that technical or complicated but I think the website has some geological restrictions.

I had to use a VPN for the site to load. I even used another web browser and I used my laptop but it  still didn't work.

I had to use a VPN for it to work

At first, I thought it was my web browser cause I use Brave for browsing but then I switched to chrome but it showed the same error message.

That's when I used a laptop and it showed the same error message so I tried the VPN that's when it worked.

It'd be great if you could work on that, below are some screenshots showing the error message.

![Screenshot_20240825-151407.jpg](https://github.com/user-attachments/assets/ea54ddd9-d5ea-4f0e-9a63-af0004faf23b)

![IMG_20240825_155501_025.jpg](https://github.com/user-attachments/assets/8fb873aa-f62d-4a64-b6b4-115dd26a06d0)

**Comment by netdragonx** [comment]
Hmm... we use Vercel but I don't think we've blocked any geos. Feel free to follow up on our Discord support channel.

**Comment by gatedude** [comment]
> Hmm... we use Vercel but I don't think we've blocked any geos. Feel free to follow up on our Discord support channel.
 
I think the site has some geological restrictions, I had to use a VPN for it to work.

Also this is part of the Bounty that was posted on Farcaster.
